[package]
name = "oro-jackson"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
axum = "0.7.9"
rust-embed = "8.5.0"
axum-embed = "0.1.0"
axum-extra = { version = "0.9.6", features = ["cookie"]}
axum-macros = "0.4.2"
askama = { version = "0.12.1", features = ["serde-json"] }
askama_axum = "0.4.0"
serde = { version= "1.0.217", features = ["derive"]}
serde_json = "1.0.134"
dotenvy = "0.15.7"
uuid = { version = "1.11.0", features = ["v4"] }
