[package]
name = "oro-jackson"
edition = "2021"

[dependencies]
askama = "0.12.1"
askama_axum = "0.4.0"
axum = "0.7.9"
axum-extra = { version = "0.9.6", features = ["cookie"]}
axum-macros = "0.4.2"
clap = { version = "4.5.23", features = ["derive"] }
dotenvy = "0.15.7"
mime_guess = "2.0.5"
rust-embed = "8.5.0"
serde = { version= "1.0.217", features = ["derive"]}
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }
